-- ============================================================================
-- Migration 028: Fix Projects Table Sequence (PostgreSQL)
-- Description: Reset the projects table sequence to fix duplicate key error
-- Date: 2025-11-06
-- Database: PostgreSQL
-- ============================================================================

-- PROBLEM:
-- Error: duplicate key value violates unique constraint "projects_pkey"
-- Detail: Key (id)=(4) already exists.
-- 
-- This happens when the SERIAL sequence counter is behind the actual max ID
-- in the table. When inserting a new row, PostgreSQL tries to use the next
-- sequence value (e.g., 4), but that ID already exists in the table.

-- SOLUTION:
-- Reset the sequence to the maximum ID + 1

-- ============================================================================
-- Step 1: Check current sequence value and max ID
-- ============================================================================

-- Show current sequence value and max ID
SELECT
  'Current sequence value' AS info,
  last_value AS value
FROM projects_id_seq
UNION ALL
SELECT
  'Max ID in table (includes projects + subprojects)',
  COALESCE(MAX(id), 0)
FROM projects;

-- ============================================================================
-- Step 2: Reset the sequence to max ID + 1
-- ============================================================================

-- This will set the sequence to the maximum ID in the table + 1
-- So the next INSERT will use a value that doesn't exist yet
SELECT setval('projects_id_seq', COALESCE((SELECT MAX(id) FROM projects), 0) + 1, false);

-- ============================================================================
-- Step 3: Verification
-- ============================================================================

-- Verify the sequence was reset correctly
SELECT 
  'Sequence after reset' AS info,
  last_value AS value
FROM projects_id_seq;

-- Test that we can insert a new project (this should work now)
-- Uncomment to test:
/*
INSERT INTO projects (project_id, project_name, status, created_by)
VALUES ('TEST-001', 'Test Project', 'Active', 'AM-0001');

-- Clean up test data
DELETE FROM projects WHERE project_id = 'TEST-001';
*/

-- ============================================================================
-- NOTES
-- ============================================================================

-- This migration fixes the immediate issue, but to prevent it from happening
-- again, we should ensure that:
-- 1. We never manually insert rows with specific ID values
-- 2. We always let PostgreSQL auto-generate the ID using the sequence
-- 3. If we import data, we reset the sequence after import

-- The sequence name is automatically generated by PostgreSQL as:
-- {table_name}_id_seq

-- To check all sequences in the database:
-- SELECT * FROM information_schema.sequences WHERE sequence_schema = 'public';

-- To reset all sequences at once (use with caution):
/*
SELECT 
  'SELECT setval(''' || sequence_name || ''', COALESCE((SELECT MAX(id) FROM ' || 
  REPLACE(sequence_name, '_id_seq', '') || '), 0) + 1, false);'
FROM information_schema.sequences 
WHERE sequence_schema = 'public' 
  AND sequence_name LIKE '%_id_seq';
*/

